### ISSUE TITLE
device registry example - customImages.yaml

### ISSUE THREAD

**Issue by boaks** [eclipse/packages#128]
I would like to just use my own builds/versions (hopefully from my local container registry localhost:32000, see issue #127 ) of hono.

```yaml
deviceRegistryExample:
  imageName: my-custom-registry/hono-service-device-registry-custom
  imageTag: 1.4.0-SNAPSHOT

authServer:
  imageName: eclipse/hono-service-auth
  imageTag: 1.4.0-SNAPSHOT

adapters:
  amqp:
    imageName: eclipse/hono-adapter-amqp-vertx
    imageTag: 1.4.0-SNAPSHOT
  coap:
    imageName: eclipse/hono-adapter-coap-vertx
    imageTag: 1.4.0-SNAPSHOT
  http:
    imageName: eclipse/hono-adapter-http-vertx
    imageTag: 1.4.0-SNAPSHOT
  kura:
    imageName: eclipse/hono-adapter-kura
    imageTag: 1.4.0-SNAPSHOT
  mqtt:
    imageName: eclipse/hono-adapter-mqtt-vertx
    imageTag: 1.4.0-SNAPSHOT
  lora:
    imageName: eclipse/hono-adapter-lora-vertx
    imageTag: 1.4.0-SNAPSHOT
```

My feeling is, this example from the README.md would use a custom "deviceRegistryExample", which is not available on my system. So what is the default "deviceRegistryExample" of the 1.4.0-SNAPSHOT ?

**Comment by boaks** [comment]
Is there a shortcut to use the "1.4.0-SNAPSHOT" images from the local registry (localhost:32000), if no other customization is required?

**Comment by boaks** [comment]
works with

```yaml
deviceRegistryExample:
  imageName: localhost:32000/eclipse/hono-service-device-registry-file
  imageTag: 1.4.0-SNAPSHOT
```
