### ISSUE TITLE
Inconsistency in protocol adapter to messaging network authentication configuration

### ISSUE THREAD

**Issue by LuLeRoemer** [eclipse/packages#167]
I think I found an inconsistency in the configuration of the AMQP messaging network authentication.

I am trying to substitute the truststore used by the dispatch router for SASL EXTERNAL authentication. From my `values.yaml`:
```yaml
hono:
  amqpMessagingNetworkExample:
    dispatchRouter:
      trustStore: /etc/certs/truststore.pem
      certFile: /etc/certs/cert.pem
      keyFile: /etc/certs/key.pem
      extraSecretMounts:
        other:
          secretName: qpid-secret
          mountPath: /etc/certs
```
I assume this is working, as the protocol adapters can no longer connect to the dispatch router. I am getting the following error in the dispatch router:
```
SERVER (info) [C7] Connection from 10.244.0.50:39138 (to 0.0.0.0:5673) failed: amqp:connection:framing-error SSL Failure: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
```
and in the http protocol adapter:
```
WARN  o.e.h.client.impl.HonoConnectionImpl - attempt to connect to server [hono-dispatch-router:5673, role: AMQP Messaging Network] failed
javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
...
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
This alone is as expected.
Unfortunately, I was not able to find a setting to also replace the protocol adapter's client certificates/truststore for authenticating to the messaging network. I know that I can modify the `amqpMessagingNetworkSpec` properties. However, this only seems to take effect in case the example messaging network is disabled entirely by setting `amqpMessagingNetworkExample.enabled` to `false`. I tried the following (`values.yaml`):
```yaml
hono:
  adapters:
    amqpMessagingNetworkSpec:
      keyStorePath: /amqp/keystore.p12
      keyStorePassword: 123456
```
Looking at how the `application.yml`, as part of the adapter Secret is assembled, you can see that the amqpMessagingNetworkSpec is considered only, if `amqpMessagingNetworkExample` is disabled, which proves my observation, I guess. From `_helpers.tpl`:
```yaml
messaging:
{{- if .dot.Values.amqpMessagingNetworkExample.enabled }}
  name: Hono {{ $adapter }}
  amqpHostname: hono-internal
  host: {{ .dot.Release.Name }}-dispatch-router
  port: 5673
  keyPath: /etc/hono/key.pem
  certPath: /etc/hono/cert.pem
  trustStorePath: /etc/hono/trusted-certs.pem
  hostnameVerificationRequired: false
{{- else }}
  {{- required ".Values.adapters.amqpMessagingNetworkSpec MUST be set if example AQMP Messaging Network is disabled" .dot.Values.adapters.amqpMessagingNetworkSpec | toYaml | nindent 2 }}
{{- end }}
```
I also tried replacing the certificates at `/etc/hono/`, using an extra secret mount in the adapter deployment. However, this is not working either, as this mount would erase all existing files in the directory, such as the `application.yml`.
It would be nice to have the option of replacing protocol adapter client certificates/truststore along with the `hono.amqpMessagingNetworkExample.dispatchRouter.trustStore` property, as it otherwise appears to be useless, unless I made a mistake.
