### ISSUE TITLE
Device registry misses messaging config (noticed on file based)

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/packages#204]
The device registry secret (`hono-service-device-registry-secret.yaml`) reference the `amqpmessagingNetworkClientConfig` in the following line:
```
      {{- include "hono.amqpMessagingNetworkClientConfig" $args | nindent 6 }}
```
This line should include following config (when you are using the default config and using minikube):
```
  messaging:
    name: Hono adapter-lora-vertx
    amqpHostname: hono-internal
    host: eclipse-hono-dispatch-router
    port: 5673
    keyPath: /etc/hono/key.pem
    certPath: /etc/hono/cert.pem
    trustStorePath: /etc/hono/trusted-certs.pem
    hostnameVerificationRequired: false
```
However, this does not get included.
