### ISSUE TITLE
[Hono] Prometheus based resource limit check can't be used with native images

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#230]
The native image variant of the protocol adapters fail to pick up the Prometheus server configuration during start up, thus falling back to the noop resource limit checks.

**Comment by sophokles73** [comment]
The reason seems to be that the corresponding configuration properties in application.yaml
```yml
resource-limits:
  prometheus-based:
    host: prometheus
```
use kebab case instead of camel case.
