### ISSUE TITLE
Ditto: Simplify tracing configuration

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#414]
It would be helpful to simplify the tracing configuration in the Ditto chart. Currently, corresponding env variables have to be set for each of the relevant Ditto components. 
In the context of the cloud2edge deployment (using the Hono Jaeger backend example enabled via `hono.jaegerBackendExample.enabled=true`), this would currently look like this:
```
ditto:
  concierge:
    extraEnv:
      - name: DITTO_TRACING_ENABLED
        value: "true"
      - name: DITTO_TRACING_SAMPLER
        value: "always"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://c2e-jaeger-collector:4317"
  connectivity:
    extraEnv:
      - name: DITTO_TRACING_ENABLED
        value: "true"
      - name: DITTO_TRACING_SAMPLER
        value: "always"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://c2e-jaeger-collector:4317"
  things:
    extraEnv:
      - name: DITTO_TRACING_ENABLED
        value: "true"
      - name: DITTO_TRACING_SAMPLER
        value: "always"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://c2e-jaeger-collector:4317"
# ...
```
Having _one_ tracing configuration, getting applied to all components, would make the overall configuration easier here.

I could imagine having
```
  tracing: {}
  #  enabled: true
  #  sampler: always
  #  samplerProbability:
  #  samplerThroughput:
  #  otlpEndpoint: "http://jaeger-collector:4317"
```
properties below `global` and the individual component properties, referring to the configuration options listed in the [Ditto tracing documentation](https://www.eclipse.org/ditto/installation-operating.html#tracing).

A further step might be adding support for deploying a Jaeger all-in-one container (like with Hono `hono.jaegerBackendExample.enabled`) for easy demonstration/testing purposes. With that enabled, a default tracing config containing `enabled=true` and an `always` sampler could be used.
