### ISSUE TITLE
nodeSelector, tolerations and serviceAccounts for deployments/statefulsets

### ISSUE THREAD

**Issue by burhanuguz** [eclipse/packages#445]
Hi,

To install hono in production environment effectively, we need to have nodeSelectors, tolerations and serviceAccount definitions in the deployment/statefulset templates.

Since there is no implementation of it, we edited those templates manually and add values to the values yaml. We are deploying every hono deployment/statefulsets to the same nodes so we only put nodeSelector and tolerations variables in those templates. It would be much better if you could add those variables to each deployment/statefulset with _helpers.tpl templating.

```yaml
spec:
  nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
  tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
  serviceAccount: {{ .Values.serviceAccountName }}
```
