### ISSUE TITLE
Update cloud2edge chart to use the latest Hono and Ditto version

### ISSUE THREAD

**Issue by jpforevers** [eclipse/packages#553]
Please update cloud2edge chart to use the latest Hono and Ditto version

**Comment by jpforevers** [comment]
@sophokles73 @ctron @thjaeckle Please help.

**Comment by kalinkostashki** [comment]
Hi,

you can just update the images in the values.yaml file using the following logic:
```
ditto:
  <service-name>:
    image:
      repository: docker.io/eclipse/<service-name>
      tag: 3.6.0(or any version you like)
```
The above approach will give you what you want, but you won't have the configuration for the WoT. You would have to import them using the above approach to you values.yaml or wrapping helm chart in order to do this.
But since maintenance isn't very active here I would suggest to use the separate helm charts of both services.
