### ISSUE TITLE
Restructure folders and setup package zero umbrella chart

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/packages#7]
As proposed in https://github.com/eclipse/packages/issues/2#issuecomment-558029074 the structure of the repo shall be:

```
charts/
  ditto/
    templates/
    Chart.yaml
    requirements.yaml
    ...
  hono/
    templates/
    Chart.yaml
    requirements.yaml
    ...
homepage/
packages/
  zero/
    Chart.yaml
    requirements.yaml
```

Establish the "umbrella" Charts for packages similar (or even same) to this approach: 
https://github.com/CodeJjang/helm-microservices-example

The requirements in umbrella chart in `packages/zero/requirements.yaml` could link to the charts like:
```yaml
dependencies:
  - name: ditto
    version: 1.0.0-snapshot
    repository: file://../../charts/ditto
  - name: hono
    version: 1.0.0-snapshot
    repository: file://../../charts/hono
```
