### ISSUE TITLE
Configure hono's coap-adapter using "Californium.properties"?

### ISSUE THREAD

**Issue by boaks** [eclipse/packages#89]
Is it possible, to add a"Californium.properties" file in order to tune the hono coap-adapter?
What must be adapted in order to do so?

**Comment by sophokles73** [comment]
You'll need to put it into a kubernetes secret which you need to manually deploy to the same name space that Hono is installed to.
Then you can customize the helm chart to mount this secret into the CoAP adapter container and use the file. Th easiest way to do this is to create a yaml file that looks like this:
```yaml
adapters:
  coap:
    extraSecretMounts:
      mySecret:
        secretName: "the-name-of-the-secret-you-created"
        mountPath: "/etc/extra-secret"
    hono:
      coap:
        bindAddress: "0.0.0.0"
        port: 5684
        tenantIdleTimeout: "1h"
        secureNetworkConfig: "/etc/extra-secret/MySecureCalifornium.properties"
```
When installing Hono using helm, the file can be referenced like this:
```bash
helm install -f my-californium-customization.yaml hono eclipse-iot/hono
```
